### Run test locally
POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "darkside",
  "token": "secret",
  "ratePerSecond": 15,
  "testCount": 3000,
  "processingTimeMillis": 2500
}

# 6
curl http://localhost:1234/test/run \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "serviceName": "darkside",
        "token": "...",
          "ratePerSecond": 7,
          "testCount": 800,
          "processingTimeMillis": 3500
    }'


### Stop running test to save time and resources
# @timeout 120
POST http://localhost:1234/test/stop/darkside
