### Run test locally
POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "darkside",
  "token": "secret",
  "ratePerSecond": 15,
  "testCount": 3000,
  "processingTimeMillis": 2500
}

curl http://localhost:1234/test/run \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "serviceName": "darkside",
        "token": "..",
        "ratePerSecond": 100,
        "testCount": 5000,
        "processingTimeMillis": 20000
    }'

Аккаунт: "acc-9"

  {
    "serviceName": "darkside",
    "accountName": "acc-9",
    "parallelRequests": 50,
    "rateLimitPerSec": 120,
    "price": 30,
    "averageProcessingTime": "PT0.5S"
  },

Тест:
{
  "ratePerSecond": 100,
  "testCount": 5000,
  "processingTimeMillis": 20000
}

mvn dependency:go-offline && mvn package && java -jar target/demo-0.0.1-SNAPSHOT.jar


export PAYMENT_SERVICE_NAME=darkside
export PAYMENT_TOKEN=...
export PAYMENT_ACCOUNTS=acc-9
export PAYMENT_HOST=localhost
export PAYMENT_PORT=1234



### Stop running test to save time and resources
# @timeout 120
POST http://localhost:1234/test/stop/darkside
